apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-deploy-ui-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: pipelines-vote-ui
  - name: git-url
    value: https://github.com/openshift/pipelines-vote-ui.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/pipelines-vote-ui
  - name: SONARQUBE_URL
    value: http://172.203.224.21:9002/
  - name: SONARQUBE_TOKEN
    value: sqp_b77a634dd254573b9349c5dd8d4af686c6bfe5a6
  - name: projectKey
    value: pipelines-vote-ui
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
