# New Pipeline Parametarized

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: deployment-name
      type: string
      description: Name of the deployment to be patched
    - name: git-url
      type: string
      description: URL of the Git repository for the code of deployment
    - name: git-revision
      type: string
      description: Revision to be used from the repo of the code for deployment
      default: main
    - name: IMAGE
      type: string
      description: Image to be built from the code
    - name: SONARQUBE_URL
      type: string
      description: SonarQube server URL
    - name: SONARQUBE_TOKEN
      type: string
      description: SonarQube authentication token
    - name: projectKey
      type: string
      description: SonarQube project key

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)

    - name: sonar-scanning
      taskSpec:
        params:
          - name: git-url
            type: string
          - name: git-revision
            type: string
          - name: SONARQUBE_URL
            type: string
          - name: SONARQUBE_TOKEN
            type: string
          - name: projectKey
            type: string
        steps:
          - name: git-clone
            image: alpine/git:latest
            script: |
              #!/bin/sh
              git clone $(params.git-url) /workspace/source
              cd /workspace/source
              git checkout $(params.git-revision)
          - name: sonar-scanner
            image: sonarsource/sonar-scanner-cli:latest
            env:
              - name: SONAR_HOST_URL
                value: "$(params.SONARQUBE_URL)"
              - name: SONAR_TOKEN
                value: "$(params.SONARQUBE_TOKEN)"
              - name: SONAR_PROJECT_KEY
                value: "$(params.projectKey)"
            script: |
              #!/bin/sh
              mkdir test
              cd test
              cp -r /workspace/source .
              cd source
              sonar-scanner -Dsonar.projectKey=$(params.projectKey) \
                             -Dsonar.sources=. \
                             -Dsonar.host.url=$SONAR_HOST_URL \
                             -Dsonar.login=$SONAR_TOKEN
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: SONARQUBE_URL
          value: $(params.SONARQUBE_URL)
        - name: SONARQUBE_TOKEN
          value: $(params.SONARQUBE_TOKEN)
        - name: projectKey
          value: $(params.projectKey)
      runAfter:
        - fetch-repository

    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - sonar-scanning

    - name: scan-image
      taskSpec:
        params:
          - name: IMAGE
            type: string
        steps:
          - name: trivy
            image: aquasec/trivy:latest
            env:
              - name: TRIVY_INSECURE
                value: "true"
            script: |
              #!/bin/sh
              trivy image --no-progress $(params.IMAGE)
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - build-image

    - name: apply-manifests
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - scan-image

    - name: update-deployment
      taskRef:
        name: update-deployment
      params:
        - name: deployment
          value: $(params.deployment-name)
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - apply-manifests
